main/urls.py
from django.urls import path
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user
from main.views import increase_product, remove_product, delete_product, edit_product
from main.views import get_product_json, add_product_ajax, delete_product_ajax
from main.views import create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product/', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('increase_product/<int:id>/', increase_product, name='increase_product'),
    path('remove_product/<int:id>/', remove_product, name='remove_product'),
    path('delete_product/<int:id>/', delete_product, name='delete_product'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete-product-ajax/<int:id>/', delete_product_ajax, name='delete_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

vineyard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='image/')

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "amount", "description", "image"]

main/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, JsonResponse
from main.forms import ProductForm
from django.urls import reverse
from django.core import serializers
from main.models import Product
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import datetime

# Create your views here.

@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'class': 'PBP A',
        'products': products,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST , request.FILES or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def increase_product(request, id):
    product = Product.objects.get(pk = id)
    product.amount += 1
    product.save()
    messages.success(request, product.name + '  has been successfully added!')
    return HttpResponseRedirect(reverse('main:show_main'))

def remove_product(request, id):
    product = Product.objects.get(pk = id)
    if product.amount == 1 :
        product.delete()
    if product.amount > 1 :
        product.amount -= 1
        product.save()
    messages.success(request, product.name + ' has been successfully reduced!')
    return HttpResponseRedirect(reverse('main:show_main'))

def delete_product(request, id):
    # Get data berdasarkan ID
    product = Product.objects.get(pk = id)
    # Hapus data
    product.delete()
    # Kembali ke halaman awal
    messages.success(request, product.name + ' has been successfully deleted!')
    return HttpResponseRedirect(reverse('main:show_main'))

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def get_product_json(request):
    product_item = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        image = request.FILES.get("image")
        user = request.user

        new_product = Product(name=name, amount=amount, description=description, user=user, image=image)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_product_ajax(request, id):
    if request.method == 'DELETE':
        product = Product.objects.get(pk=id)
        product.delete()
        return JsonResponse({'message': 'Product deleted successfully.'})

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %}

{% block meta %}
<style>
    body {
        background: #141519 !important;
    }

    .card-body {
        background: #e8dcd5 !important;
    }
</style>

<title>Add New Product</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <h1 class="card-title text-center">Add New Product</h1>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="{{ form.name.id_for_label }}" class="form-label">Name:</label>
                            {{ form.name }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.description.id_for_label }}" class="form-label">Description:</label>
                            {{ form.description }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.price.id_for_label }}" class="form-label">Amount:</label>
                            {{ form.amount }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.image.id_for_label }}" class="form-label">Image:</label>
                            {{ form.image }}
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn" style="background-color: #141519; color: #e8dcd5">Add Product</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<style>
    body {
        background: #141519 !important;
    }

    .card-body {
        background: #e8dcd5 !important;
    }
</style>

<title>Edit Product</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <h1 class="card-title text-center">Edit Product</h1>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="{{ form.name.id_for_label }}" class="form-label">Name:</label>
                            {{ form.name }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.description.id_for_label }}" class="form-label">Description:</label>
                            {{ form.description }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.price.id_for_label }}" class="form-label">Amount:</label>
                            {{ form.amount }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.image.id_for_label }}" class="form-label">Image:</label>
                            {{ form.image }}
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn" style="background-color: #141519; color: #e8dcd5">Edit Product</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<style>
    body {
    background: #141519 !important;
    }

    .card-body {
        background: #e8dcd5 !important;
    }
</style>

<title>Login</title>
{% endblock meta %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <h1 class="card-title text-center">Login</h1>
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="username" class="form-label">Username:</label>
                            <input type="text" name="username" id="username" class="form-control" placeholder="Username" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Password:</label>
                            <input type="password" name="password" id="password" class="form-control" placeholder="Password" required>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn" style="background-color: #141519; color: #e8dcd5">Login</button>
                        </div>
                    </form>
                    <p class="mt-3 text-center">Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}

<style>
    .navbar-brand {
        color: #e8dcd5;
    }

    .jumbotron {
        background-color: rgba(232, 220, 213, 0.7); 
        padding: 2rem 1rem;
        text-align: center;
        height: 30vh;
        display: flex; 
        flex-direction: column; 
        justify-content: center; 
        position: relative;
    }

    .jumbotron::before {
        content: "";
        background-size: cover;
        height: 100%;
        width: 100%;
        position: absolute;
        top: 0;
        left: 0;
        filter: blur(2px); 
        z-index: -1; 
    }

    .title{
        font-weight: 800;
        font-size: 40px;
        margin-bottom: 10px;
    }

    .caption {
        font-size: 24px;
        color: #e8dcd5;
    }

    .product-card {
        display: flex;
        background-color: #e8dcd5;
        border: 1px solid #e0e0e0;
        margin: 10px;
        padding: 10px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        height: 210px;
        width: 100%;
    }

    .product-image {
        flex: 2;
        margin-right: 20px;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .product-image img {
        max-width: 100%;
        max-height: 100%;
        height: auto;
        border: 1px solid #ccc;
    }

    .product-details {
        flex: 2;
    }

    .product-name {
        font-weight: bold;
        font-size: 24px;
        margin-bottom: 10px;
    }

    .product-description {
        font-size: 16px;
        margin-bottom: 10px;
    }

    .product-amount {
        font-size: 18px;
        margin-bottom: 10px;
    }

    .product-buttons {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .product-button-dark,
    .product-button-light {
        padding: 3px 8px;
        border: none;
        cursor: pointer;
        margin: 2px;
        border-radius: 10px;
    }

    .product-button-dark {
        background-color: #141519;
        color: #e8dcd5;
    }

    .product-button-light {
        background-color: #e8dcd5;
        color: #141519;
    }

    .product-actions a {
        text-decoration: none;
    }

    .center-content {
        display: flex;
        flex-direction: column;
        align-items: center;
        text-align: center;
        margin: 10px;
    }

    .last-login {
        color: #e8dcd5;
    }

    .modal-content {
        background: #e8dcd5;
    }

    img {
        max-height: 80%;
    }

    body {
        background: #141519;
    }
</style>
    <!-- NavBar -->
    <nav class="navbar navbar-expand-lg shadow" style = "background-color: #141519">
        <div class="container">
            <span class="navbar-brand mb-0 h1;">{{name}}</span>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:logout' %}">
                        <button class="btn btn-outline-secondary" style="color: #e8dcd5;" type="submit">Logout</button>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- End of NavBar-->

    <!-- Jumbotron -->
    <div class="jumbotron">
        <div class="jumbotron-content">
            <h1 class="title">VINEYARD</h1>
            <hr class="caption">
            <p>Harvested with Care, Delivered with Freshness: Your Online Oasis for Farm-to-Table Goodness!</p>
        </div>
    </div>
    <!-- End of Jumbotron -->

    <!-- Card -->
    <div class="container">
        <div class="row" id="product_table">
        </div>
    </div>    
    <!-- End of Card -->

    <!-- Modal Form Add Product AJAX -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="image" class="col-form-label">Image:</label>
                            <input type="file" class="form-control" id="image" name="image">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn" id="button_add" style="background-color: #141519; color: #FFF" data-bs-dismiss="modal">Add Product</button>
                </div>
            </div>
        </div>
    </div>
    <!-- End of Modal Form Add Product AJAX -->

    <!-- Add more product -->
    <div class="center-content">
        <p class="last-login">Last login: {{ last_login }}</p>
        <button type="button" class="product-button-light" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>
    </div>

    <a href="{% url 'main:create_product' %}">
        <button class="button">
            Add New Item
        </button>
    </a>

    <!-- End of Add more product -->

    <script>
    async function getProducts() {
        return fetch("get-product/").then((res) => res.json())
    }

    async function refreshProducts() {
        document.getElementById("product_table").innerHTML = ""
        const products = await getProducts()
        let htmlString = ` `
        products.forEach((item) => {
            htmlString += `
                <div class="col-md-6 col-lg-6 col-sm-12">
                    <div class="product-card">
                        <div class="product-image">
                            <img src="media_root/${item.fields.image}" alt="Product Image">
                        </div>
                        <div class="product-details">
                            <div class="product-name">${item.fields.name}</div>
                            <div class="product-description">${item.fields.description}</div>
                            <div class="product-amount">In Stock: ${item.fields.amount}</div>
                        </div>
                        <div class="product-actions mt-auto">
                            <button class="product-button-dark" onclick="increaseProduct(event, ${item.pk})">+</button>
                            <button class="product-button-dark" onclick="removeProduct(${item.pk})">-</button>
                            <button class="product-button-dark" onclick="editProduct(${item.pk})">Edit</button>
                            <button class="product-button-dark" onclick="deleteProduct(${item.pk})">Delete</button>
                        </div>
                    </div>
                </div>`;
        });

        document.getElementById("product_table").innerHTML = htmlString
    }

    refreshProducts()

    function addProduct() {
        fetch("/create-product-ajax/", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }

    document.getElementById("button_add").onclick = addProduct

    // Fungsi untuk menambahkan produk
    function increaseProduct(event, productId) {
        event.preventDefault();
        fetch("/increase_product/"+productId+"/")
        .then(refreshProducts)    
    }

    // Fungsi untuk mengurangi produk
    function removeProduct(productId) {
        fetch("/remove_product/"+productId+"/")
        .then(refreshProducts)
    }

    // Fungsi untuk mengedit produk
    function editProduct(productId) {
        fetch("/edit_product/"+productId+"/")
        .then(refreshProducts)
    }

    // Fungsi untuk menghapus produk
    async function deleteProduct(productId) {
        if (confirm("Are you sure you want to delete this product?")) {
            fetch("/delete-product-ajax/"+productId+"/", {
                method: "DELETE",
            })
            .then(res => res.json())
            .then(data => {
                refreshProducts();
                alert(data.message);
            })
        }
    }
    </script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<style>
    body {
    background: #141519 !important;
    }

    .card-body {
        background: #e8dcd5 !important;
    }
</style>

<title>Register</title>
{% endblock meta %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <h1 class="card-title text-center">Register</h1>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="text-center">
                            <button type="submit" class="btn" style="background-color: #141519; color: #e8dcd5">Register</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}